( cd ksupport ; sh kdesupport.build )
( cd kdelibs ; sh kdelibs.build )
( cd kdebase ; sh kdebase.build )
( cd kadmin ; sh kdeadmin.build )
( cd kdegames ; sh kdegames.build )
( cd kgraphic ; sh kdegraphics.build )
( cd kmedia ; kdemultimedia.build )
#( cd knetwork ; ./kdenetwork.build )
#( cd kdetoys ; ./kdetoys.build )
#( cd kdeutils ; ./kdeutils.build )
#( cd korganiz ; ./korganizer.build )
