( cd ksupport ; sh kdesupport.build )
#( cd kdelibs ; ./kdelibs.build )
#( cd kdebase ; ./kdebase.build )
#( cd kadmin ; ./kdeadmin.build )
#( cd kdegames ; ./kdegames.build )
#( cd kgraphic ; ./kdegraphics.build )
#( cd kmedia ; ./kdemultimedia.build )
#( cd knetwork ; ./kdenetwork.build )
#( cd kdetoys ; ./kdetoys.build )
#( cd kdeutils ; ./kdeutils.build )
#( cd korganiz ; ./korganizer.build )
